theme: jekyll-theme-minimal
title: "Росенко Андрей"
description: "Backend-разработчик | 18 лет"
lang: ru
logo: images/cuddle_me_cutted.PNG
city: "Санкт-Петербург"
phone_number: "+79932172517"
email: "lora.de.mosf@gmail.com"
