theme: jekyll-theme-minimal
title: "Росенко Андрей"
description: "Software Engineer, 19 лет"
lang: ru
logo: images/temp.jpg
city: "Санкт-Петербург"
phone_number: "+79932172517"
email: "lora.de.mosf@gmail.com"
